import type { ExtensionManifest } from "../extensions/manifest.ts";
// BROKERED_FETCH_METHOD is INTERPOLATED into the emitted script rather than restated as a literal:
// D29(a) confines that string to `toolgen-types.ts`, and an emitter that hardcoded it would red the
// static audit the moment Task 17 lands.
import { BROKERED_FETCH_METHOD, ToolgenError, type ToolInputSchema } from "./toolgen-types.ts";

/**
 * The ONLY generated-manifest constructor (static rule D29(b)).
 *
 * `permissions.network` is `[]` BY CONSTRUCTION and a requested grant is REJECTED rather than
 * dropped — I33's `buildExecPolicy` rule, for the same reason. That empty set is what drives
 * `--unshare-net` on Linux, the absent `(allow network*)` block on macOS and the absent
 * `internetClient` capability on Windows, which together are why a raw `fetch()` in the generated
 * body fails at the OS on all three platforms (spec § 4.3). It is also why spec § 3's Windows
 * per-host problem does not apply: there are no hosts to filter.
 */
export function buildGeneratedManifest(
  toolId: string,
  opts: {
    readonly network?: readonly string[];
    readonly scriptDir?: string;
    /**
     * Paths the sandbox must grant READ so the child can load its interpreter AT ALL.
     *
     * Not an optimisation. On Windows the AppContainer helper writes one ACE per granted path, so a
     * binary outside every grant is simply unreadable and the child dies before running a line —
     * exit 68, no stdout, no stderr. Linux hides this because bwrap binds the system tree by
     * default, which is exactly why it must be stated. `exec-gate.ts` passes
     * `runtime.requiredReadPaths()` here for the same reason.
     */
    readonly runtimeReadPaths?: readonly string[];
  } = {},
): ExtensionManifest {
  if (opts.network !== undefined && opts.network.length > 0) {
    throw new ToolgenError(
      "ERR_TOOLGEN_NETWORK_UNSUPPORTED",
      "a generated tool cannot be granted network — it reaches the network only through the broker",
    );
  }
  return {
    id: `toolgen.${toolId}`,
    version: "0.0.0",
    permissions: {
      network: [],
      filesystem: {
        // Its own script directory plus the interpreter's paths, and nothing else. NO node_modules
        // grant: the emitted script imports nothing (see `emitToolScript`), which is what keeps this
        // grant this small.
        read: [
          ...(opts.scriptDir === undefined ? [] : [opts.scriptDir]),
          ...(opts.runtimeReadPaths ?? []),
        ],
        write: [],
      },
    },
    updateChannel: "stable",
  };
}

/**
 * Wrap the model-authored BODY in a Nimbus-authored skeleton.
 *
 * The transport, the `nimbusFetch` helper and the manifest are all ours; the model fills a hole in
 * a template it does not control. It is not required to cooperate — if the body ignores
 * `nimbusFetch` and calls `fetch()` directly, the sandbox refuses it — but supplying the helper is
 * what makes the cooperative path the easy one.
 *
 * The body is embedded VERBATIM: these are the bytes the owner approved.
 */
export function emitToolScript(input: {
  readonly toolId: string;
  readonly toolName: string;
  readonly description: string;
  readonly body: string;
  readonly inputSchema: ToolInputSchema;
}): string {
  return `// GENERATED by Nimbus toolgen for ${input.toolId} — do not edit.
// Zero imports, deliberately: this file runs from the ephemeral script store, which has no
// node_modules and is granted read access to nothing else. See the plan's Task 7 note.
const __send = (msg) => { process.stdout.write(JSON.stringify(msg) + "\\n"); };
const __pending = new Map();
let __seq = 0;

/**
 * The only route out of this process. This process has NO network — a raw fetch() fails at the OS.
 */
async function nimbusFetch(url, init = {}) {
  const id = "r" + String(++__seq);
  return await new Promise((resolve, reject) => {
    __pending.set(id, { resolve, reject });
    __send({ id, method: ${JSON.stringify(BROKERED_FETCH_METHOD)}, params: { url, ...init } });
  });
}

async function __invoke(args) {
${input.body}
}

let __buf = "";
// Decode stdin as UTF-8 ONCE, at the stream, so a multi-byte character split across two \`data\`
// events is reassembled instead of becoming U+FFFD on both sides. Per-chunk \`chunk.toString()\`
// corrupts it silently: the torn line then fails \`JSON.parse\` and is dropped by the \`catch\`
// below, so a brokered-fetch reply or a \`call\` request carrying non-ASCII text is simply lost and
// its pending promise never settles. Setting the encoding makes \`data\` deliver complete strings.
process.stdin.setEncoding("utf8");
process.stdin.on("data", async (chunk) => {
  __buf += chunk;
  let nl;
  while ((nl = __buf.indexOf("\\n")) >= 0) {
    const line = __buf.slice(0, nl);
    __buf = __buf.slice(nl + 1);
    if (line.trim() === "") continue;
    let msg;
    try { msg = JSON.parse(line); } catch { continue; }
    // A reply to one of OUR outbound broker calls.
    if (msg.id !== undefined && msg.method === undefined) {
      const p = __pending.get(msg.id);
      if (p !== undefined) {
        __pending.delete(msg.id);
        if (msg.error !== undefined) p.reject(new Error(String(msg.error)));
        else p.resolve(msg.result);
      }
      continue;
    }
    // An inbound request from the gateway.
    if (msg.method === "describe") {
      __send({ id: msg.id, result: { name: ${JSON.stringify(input.toolName)}, description: ${JSON.stringify(input.description)}, inputSchema: ${JSON.stringify(input.inputSchema)} } });
    } else if (msg.method === "call") {
      try {
        __send({ id: msg.id, result: await __invoke(msg.params ?? {}) });
      } catch (err) {
        __send({ id: msg.id, error: String(err && err.message ? err.message : err) });
      }
    }
  }
});
`;
}
