/**
 * `nimbus bench` orchestrator. Parses flags, routes to surface drivers,
 * appends a HistoryLine, prints a human summary.
 *
 * See docs/superpowers/specs/2026-04-26-perf-audit-design.md §3.2 (surface
 * table), §4.1 (reference protocol), §4.5 (aggregation).
 */

import { hostname, platform, release } from "node:os";

import { runBench } from "./bench-harness.ts";
import { appendHistoryLine, type HistoryLine, type HistoryLineSurface } from "./history-line.ts";
import { runQueryLatencyOnce } from "./surfaces/bench-query-latency.ts";
import type { BenchRunOptions, BenchSurfaceId, BenchSurfaceResult, RunnerKind } from "./types.ts";

export interface BenchCliDeps {
  /**
   * Caller-supplied UUID for the run. Threaded through to the HistoryLine
   * AND to the signal-handler context factory so an interrupted run records
   * the SAME run_id it would have recorded on success — not a generic
   * "interrupted" sentinel. Generated by `bench-runner.ts` (Task 8b),
   * never by the orchestrator itself.
   */
  runId: string;
  historyPath: string;
  fixtureCacheDir?: string;
  stdout: (s: string) => void;
  stderr?: (s: string) => void;
  /** Defaults to interactive y/n prompt; tests inject a stub. */
  confirmReferenceProtocol?: () => boolean | Promise<boolean>;
  /** Defaults to env-aware lookup; tests inject a stub. */
  resolveGitSha?: () => string;
}

const SURFACE_REGISTRY = {
  "S2-a": runQueryLatencyOnce,
} as const satisfies Partial<
  Record<
    BenchSurfaceId,
    (opts: BenchRunOptions, runOpts: { cacheDir?: string }) => Promise<number[]>
  >
>;

function takeFlag(args: string[], flag: string): string | undefined {
  const i = args.indexOf(flag);
  if (i < 0 || i + 1 >= args.length) return undefined;
  return args[i + 1];
}

function hasFlag(args: string[], flag: string): boolean {
  return args.includes(flag);
}

function detectRunner(args: string[]): RunnerKind {
  if (hasFlag(args, "--reference")) return "reference-m1air";
  if (hasFlag(args, "--gha")) {
    if (process.platform === "darwin") return "gha-macos";
    if (process.platform === "win32") return "gha-windows";
    return "gha-ubuntu";
  }
  return "local-dev";
}

function defaultConfirm(): boolean {
  // No-prompt context (CI, scripted) — refuse rather than auto-approve.
  return false;
}

function defaultResolveGitSha(): string {
  return process.env["GITHUB_SHA"] ?? "unknown";
}

function resultToHistorySurface(r: BenchSurfaceResult): HistoryLineSurface {
  const out: HistoryLineSurface = { samples_count: r.samplesCount };
  if (r.p50Ms !== undefined) out.p50_ms = r.p50Ms;
  if (r.p95Ms !== undefined) out.p95_ms = r.p95Ms;
  if (r.p99Ms !== undefined) out.p99_ms = r.p99Ms;
  if (r.maxMs !== undefined) out.max_ms = r.maxMs;
  if (r.throughputPerSec !== undefined) out.throughput_per_sec = r.throughputPerSec;
  if (r.tokensPerSec !== undefined) out.tokens_per_sec = r.tokensPerSec;
  if (r.firstTokenMs !== undefined) out.first_token_ms = r.firstTokenMs;
  if (r.rssBytesP95 !== undefined) out.rss_bytes_p95 = r.rssBytesP95;
  return out;
}

function resolveSurfaces(args: string[], surfaceArg: string | undefined): BenchSurfaceId[] {
  if (hasFlag(args, "--all")) return Object.keys(SURFACE_REGISTRY) as BenchSurfaceId[];
  if (surfaceArg !== undefined) return [surfaceArg as BenchSurfaceId];
  return [];
}

export async function runBenchCli(args: string[], deps: BenchCliDeps): Promise<number> {
  const stderr = deps.stderr ?? ((s: string) => process.stderr.write(`${s}\n`));
  const surfaceArg = takeFlag(args, "--surface");
  const runsArg = takeFlag(args, "--runs");
  const corpusArg = takeFlag(args, "--corpus");
  const runs = runsArg === undefined ? 5 : Number.parseInt(runsArg, 10);
  const runner = detectRunner(args);
  const corpus =
    corpusArg === "small" || corpusArg === "medium" || corpusArg === "large"
      ? corpusArg
      : undefined;
  const opts: BenchRunOptions = {
    runs: Number.isFinite(runs) && runs > 0 ? runs : 5,
    runner,
    ...(corpus !== undefined && { corpus }),
  };

  if (runner === "reference-m1air") {
    const confirm = deps.confirmReferenceProtocol ?? defaultConfirm;
    const ok = await confirm();
    if (!ok) {
      stderr("Reference-run protocol checklist not confirmed. Refusing to record. See spec §4.2.");
      return 2;
    }
  }

  const surfaces = resolveSurfaces(args, surfaceArg);

  if (surfaces.length === 0) {
    stderr(
      "Pass --surface <id> or --all. Available surfaces: " +
        Object.keys(SURFACE_REGISTRY).join(", "),
    );
    return 2;
  }

  const surfaceResults: Record<string, HistoryLineSurface> = {};
  for (const id of surfaces) {
    const driver = SURFACE_REGISTRY[id as keyof typeof SURFACE_REGISTRY];
    if (driver === undefined) {
      stderr(`Surface ${id} has no driver registered yet (PR-B-2 work).`);
      return 2;
    }
    const runOpts = deps.fixtureCacheDir !== undefined && { cacheDir: deps.fixtureCacheDir };
    const result = await runBench(id, (o) => driver(o, runOpts || {}), opts);
    surfaceResults[id] = resultToHistorySurface(result);
    deps.stdout(
      `${id}  p95=${result.p95Ms?.toFixed(2) ?? "-"}ms  p99=${result.p99Ms?.toFixed(2) ?? "-"}ms  samples=${result.samplesCount}`,
    );
  }

  const resolveGitSha = deps.resolveGitSha ?? defaultResolveGitSha;
  const line: HistoryLine = {
    schema_version: 1,
    run_id: deps.runId,
    timestamp: new Date().toISOString(),
    runner,
    os_version: `${platform()} ${release()} (${hostname()})`,
    nimbus_git_sha: resolveGitSha(),
    bun_version: typeof Bun === "undefined" ? "unknown" : Bun.version,
    surfaces: surfaceResults as Partial<Record<BenchSurfaceId, HistoryLineSurface>>,
    ...(runner === "reference-m1air" && { reference_protocol_compliant: true }),
  };
  appendHistoryLine(deps.historyPath, line);
  return 0;
}
